SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'a%e';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'a%i';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'a%o';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'a%a';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'a%u';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'e%a';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'e%e';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'e%i';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'e%o';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'e%u';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'i%e';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'i%i';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'i%o';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'i%a';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'i%u';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'o%e';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'o%i';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'o%o';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'o%a';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'o%u';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'u%e';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'u%i';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'u%o';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'u%a';

SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'u%u';